// pages/index.js
import { useState } from 'react';

export default function HomePage() {
    const [text, setText] = useState('');
    const [apiResponse, setApiResponse] = useState('');
    const [error, setError] = useState('');
    const maxLength = 2000; // 设置最大字符长度


    const containerStyle = {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100vh',
        textAlign: 'center'
    };

    const inputStyle = {
        width: '100%', // 输入框宽度为视口宽度的一半
        height: '100%',
        padding: '100px',
        margin: '50px 0'
    };

    const buttonStyle = {
        padding: '10px 20px'
    };

    const counterStyle = {
        textAlign: 'right',
        fontSize: '0.8rem',
        marginTop: '5px',
        marginBottom: '20px'
    };


    const handleSubmit = async (event) => {
        event.preventDefault();
        setError('');
        setApiResponse('');

        if (text.trim() === '') {
            setError('Text input cannot be empty.');
            return;
        }

        try {
            const response = await fetch('/api/detectText', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ text })
            });

            if (!response.ok) {
                throw new Error(`Error: ${response.status}`);
            }

            const data = await response.json();
            setApiResponse(data);
        } catch (err) {
            setError(err.message);
        }
    };

    const handleInputChange = (e) => {
        const inputText = e.target.value;
        if (inputText.length <= maxLength) {
            setText(inputText);
        }
    };




    return (
        <div style={containerStyle}>
            <h1>GPTZERO Detecter</h1>
            <h2>You can input a text right here to dectect if it is generated by Chatgpt!</h2>
            <form onSubmit={handleSubmit}>
        <textarea
            value={text}
            onChange={handleInputChange}
            placeholder="Enter text here"
            style={inputStyle}
            rows="4"
            maxLength={maxLength} // 限定最大字符数
        />
                <div style={counterStyle}>
                    {text.length} / {maxLength}
                </div>
                <button type="submit" style={buttonStyle}>Submit</button>
            </form>
            {error && <p style={{ color: 'red' }}>Error: {error}</p>}
            {apiResponse && <p>Response: {JSON.stringify(apiResponse)}</p>}
        </div>
    );
}
